#!/bin/bash

# Build the app for linux first
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo -ldflags '-w' ../ 

# Build the vinspection image
docker build -t wumuxian/aws-slack-bot:latest .

# Remove the binary and the config file
rm aws-slack-bot

# Clear up and Push the image
images=$(docker images -q --filter "dangling=true")
echo $images
if [ "$images" != "" ]; then
docker rmi $images
fi
docker push wumuxian/aws-slack-bot
